name: "repository-checkov"
permissions: read-all

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    name: repository-checkov
    uses: honestbank/workflows/.github/workflows/checkov.yaml@main
    secrets: inherit
