name: "repository-semantic-pr"
permissions: read-all

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  repository-semantic-pr:
    name: "repository-semantic-pr"
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        name: Semantic Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
