name: "Semantic PR Repository Workflow"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: semantic-pull-request-repository-job
    uses: honestbank/workflows/.github/workflows/general-semantic-pr.yaml@main
    secrets: inherit
