name: terratest
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  terratest:
    name: terratest
    runs-on: ubuntu-latest
    env:
      TERRATEST_CONFLUENT_CLOUD_SEED_KEY: ${{ secrets.TERRATEST_CONFLUENT_CLOUD_SEED_KEY }}
      TERRATEST_CONFLUENT_CLOUD_SEED_SECRET: ${{ secrets.TERRATEST_CONFLUENT_CLOUD_SEED_SECRET }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go (1.18)
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go
      - name: Run terratest
        run: |
          cd test
          go test -v -timeout 10m
      - name: Release
        if: github.event_name == 'push'
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.3
            @semantic-release/changelog@6.0.1
